In [3]:
import pandas as pd

df = pd.read_csv('Web-Developers-Salaries-Egypt-2024.csv')
df

,Title,Salary,Years of Experiences,Work Hour,Work Type,What Is your Company,City of Company site
0,.Net Developer,15000,1,Full Time,Hybird,Egyptian,Alexandria
1,.Net Developer,311050,2,Full Time,Hybird,Egyptian,Cairo
2,.Net Developer,15000,1,Full Time,Hybird,Egyptian,Giza
3,.Net Developer,30000,2,Full Time,Hybird,Egyptian,Mansoura
4,.Net Developer,54000,3,Full Time,Hybird,Egyptian,un-known
...,...,...,...,...,...,...,...
191,Web Developer,5000,0,Full Time,On Site,Egyptian,Cairo
192,Web Developer,9000,1,Full Time,Remotley,Not Egyptian but site in egypt,Ksa
193,Wordpress Developer,14000,4,Full Time,Hybird,Egyptian,Cairo
194,Wordpress Developer,30000,3,Full Time,On Site,Egyptian,Cairo
195,Wordpress Developer,40000,3,Full Time,Remotley,Not Egyptian and site out of egypt,Uae

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 196 non-null    str
 1   Salary                196 non-null    int64
 2   Years of Experiences  196 non-null    int64
 3   Work Hour             196 non-null    str
 4   Work Type             196 non-null    str
 5   What Is your Company  196 non-null    str
 6   City of Company site  196 non-null    str
dtypes: int64(2), str(5)
memory usage: 10.8 KB

In [4]:
df2 = pd.read_csv('Cleaned_Wuzzuf_Jobs.csv')
df2

,name,company,location,type,job category
0,Human Resources Generalist,Options,"Mohandessin, Giza, Egypt","Full Time, On-site",Human Resources Generalist | Experienced | Ad...
1,Sales in freight forwarder company,MIF Logistics,"Obour City, Cairo, Egypt","Full Time, On-site",Sales in freight forwarder company | Experienc...
2,Senior Real Estate Sales Agent,BrokMark,"Smart Village, Giza, Egypt","Full Time, On-site",Senior Real Estate Sales Agent | Experienced |...
3,Product Manager,Valeurs,"Cairo, Egypt","Full Time, On-site",Product Manager | Manager | Marketing/PR/Adve...
4,Recruitment Specialist,Outsourcing Skill,"Maadi, Cairo, Egypt","Full Time, On-site",Recruitment Specialist | Experienced | Admini...
...,...,...,...,...,...
7861,Laravel PHP Developer,Confidential,"Dokki, Giza, Egypt","Full Time, On-site",Laravel PHP Developer | Experienced | IT/Soft...
7862,UI UX Designer,Confidential,"Dokki, Giza, Egypt","Full Time, On-site",UI UX Designer | Experienced | IT/Software De...
7863,AI evaluator,Translated,"Rome, Italy","Freelance / Project, Remote",AI evaluator | Entry Level | IT/Software Deve...
7864,Sales Engineer,ODA Furniture,"New Cairo, Cairo, Egypt","Full Time, On-site",Sales Engineer | Experienced | Business Devel...
7865,Tendering Engineer,INGAZ,"New Cairo, Cairo, Egypt","Full Time, On-site",Tendering Engineer | Entry Level | Sales/Reta...

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 196 non-null    str
 1   Salary                196 non-null    int64
 2   Years of Experiences  196 non-null    int64
 3   Work Hour             196 non-null    str
 4   Work Type             196 non-null    str
 5   What Is your Company  196 non-null    str
 6   City of Company site  196 non-null    str
dtypes: int64(2), str(5)
memory usage: 10.8 KB